### ISSUE TITLE
Style settings in GeoNode

### ISSUE THREAD

**Issue by nathanhilbert** [garnertb/django-classification-banner#4]
Are there any recommendations for placement in the latest GeoNode?  The template options were added to base.html.  The top navbar in Geonode is fixed position to top:0px as is the banner, which makes the banner overlap.  I added a style with a !important override to the base.html template, but that should be a quick fix.  Maybe an BANNER_STYLE="top:50px;" to be placed in the span tag of the banner would work.  Thanks.

**Comment by garnertb** [comment]
My recommendation would be to override the default django-classification-banner style in your Django project vs customizing the GeoNode stylesheet.
